
const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');

const app = express();
const port = 3001;

app.use(bodyParser.json());
app.use(cors({
  origin: 'http://localhost:4200',
  methods: ['GET', 'POST', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization']
}));



let phoneListings = [
      {
       id: 1,
        brand: "Google",
       model: "Pixel",
       imageurl: [
        "https://m.media-amazon.com/images/I/517Jv7f6mRL.jpg",
        "https://miro.medium.com/v2/resize:fit:1200/1*MqtpaibUKnFCh0HpA3t7tQ.jpeg",
        "https://lh3.googleusercontent.com/DF9S9Rh_LDhCs48k2oJnID5BdMJUsWNQ4CNOdnYj-nxjNLouBOqJJtKiXLMrhI4BwF-sjhOrw5XVdmh5SsvEWZWMvdB07AWtww=s0"
       ],
       number: "123-456-7890",
       category: "electronics",
       price: 649,
       releaseYear: 2016,
       operatingSystem: "Android 7.1",
       storageCapacity: ["32GB", "128GB"],
       ram: "4GB",
       screenSize: 5.0,
       batteryCapacity: 2770,
       processor: "Snapdragon 821",
       colorOptions: ["Quite Black", "Very Silver", "Really Blue"],
       rating: 4.5,
       connectivity: ["4G", "Wi-Fi 5", "Bluetooth 4.2", "NFC"],
       weight: 143
      },
      {
       id: 2,
       brand: "Apple",
       model: "iPhone 12",
       imageurl:  [
         "https://pamagroupsrl.it/wp-content/uploads/2024/07/dispose-dun-SSD-Sata-2.5-20.png",
         "https://refurbishedstore.it/wp-content/uploads/2024/08/311403478_medium.jpg",
         "https://www.tecnosell.com/media/catalog/product/cache/dc9ef63791129c4f1f95b5ecbb3d88d1/r/e/re1_1.jpg",
         "https://d1eh9yux7w8iql.cloudfront.net/product_images/None_649974ba-7b04-48b3-8fd8-9fa54597ae68.jpg",
         "https://it.webuy.com/product-detail/?id=SAPPI12128GBULIBB",
         "https://cdn.akakce.com/z/apple/iphone-12-mini-64-gb-mor.jpg"
       ],
       number: "987-654-3210",
       category: "electronics",
       price: 799,
       releaseYear: 2020,
       operatingSystem: "iOS 14",
       storageCapacity: ["64GB", "128GB", "256GB"],
       ram: "4GB",
       screenSize: 6.1,
       batteryCapacity: 2815,
       processor: "A14 Bionic",
       colorOptions: ["Black", "White", "Red", "Green", "Blue", "Purple"],
       rating: 4.6,
       connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.0", "NFC"],
       weight: 164
      },
      {
       id: 3,
       brand: "Samsung",
       model: "Galaxy S21",
       imageurl:  [
        "https://www.mondoaffariweb.it/media/catalog/product/cache/1/image/600x480.55555555556/9df78eab33525d08d6e5fb8d27136e95/g/a/galaxy-s21-gray128gb_8.jpg",
        "https://cdn11.bigcommerce.com/s-7a72dboqi9/images/stencil/1280x1280/products/2998/3290/R-samsungs21-BIA__68955.1616171669.jpg?c=2",
        "https://m.media-amazon.com/images/I/71Usua70bML.jpg",
        "https://cdn.shopify.com/s/files/1/0273/7927/3488/products/S21-5G-Phantom-Grey-Front_1200x.jpg?v=1610657992",
        "https://cdn.shopify.com/s/files/1/0273/7927/3488/products/S21-5G-Phantom-Grey-Back_1200x.jpg?v=1610657992",
       ],
       number: "098-765-4321",
       category: "electronics",
       price: 799,
       releaseYear: 2021,
       operatingSystem: "Android 11",
       storageCapacity: ["128GB", "256GB"],
       ram: "8GB",
       screenSize: 6.2,
       batteryCapacity: 4000,
       processor: "Exynos 2100 / Snapdragon 888",
       colorOptions: ["Phantom Gray", "Phantom White", "Phantom Violet", "Phantom Pink"],
       rating: 4.7,
       connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.0", "NFC"],
       weight: 169
      },
      {
       id: 4,
       brand: "Huawei",
       model: "P40 Pro",
       imageurl:[
         "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLjH3tn-Tx-m4z253ZCSiCDINGdgR_C6vCkA&s",
         "https://www.gizmochina.com/wp-content/uploads/2020/03/Huawei-P40-Pro-1.jpg", 
         "https://cdn.wccftech.com/wp-content/uploads/2020/01/P40-Pro.jpg",
         "https://d2e6ccujb3mkqf.cloudfront.net/92d3c870-2a0c-45cf-a327-d6d64f76c6ae-3_66174c64-c3ef-4f4e-8d6c-9d939c7cbc38.jpg",
         "https://d2e6ccujb3mkqf.cloudfront.net/3471d79a-8e04-45e2-b897-07b9867a0b3f-1_02c1f25a-2147-4608-897e-d3dccbe3ea58.jpg"
       ],
       number: "555-666-7778",
       category: "electronics",
       price: 999,
       releaseYear: 2020,
       operatingSystem: "Android 10 (no Google services)",
       storageCapacity: ["128GB", "256GB", "512GB"],
       ram: "8GB",
       screenSize: 6.58,
       batteryCapacity: 4200,
       processor: "Kirin 990 5G",
       colorOptions: ["Silver Frost", "Blush Gold", "Deep Sea Blue", "Ice White", "Black"],
       rating: 4.4,
       connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.1", "NFC"],
       weight: 209
      },
      {
       id: 5,
       brand: "Xiaomi",
       model: "Mi 11",
       imageurl:[
         "https://i01.appmifile.com/webfile/globalimg/products/m/mi-11/overview31-img03.jpg",
         "https://i01.appmifile.com/webfile/globalimg/products/m/mi-11/overview31-img02.jpg",
         "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYrt22aK3nP8rRZT96C2JK6igEuwLgqHJZow&s"
       ],
       number: "222-333-4444",
       category: "electronics",
       price: 749,
       releaseYear: 2021,
       operatingSystem: "Android 11",
       storageCapacity: ["128GB", "256GB"],
       ram: "8GB/12GB",
       screenSize: 6.81,
       batteryCapacity: 4600,
       processor: "Snapdragon 888",
       colorOptions: ["Horizon Blue", "Cloud White", "Midnight Gray"],
       rating: 4.6,
       connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.2", "NFC"],
       weight: 196
       },
       {
       id: 6,
       brand: "OnePlus",
       model: "8T Pro",
       imageurl:[
         "https://5.imimg.com/data5/SELLER/Default/2021/11/BS/RC/CL/136126444/renewed-oneplus-8-pro-glacial-green-8gb-ram-128gb-storage-.jpg",
         "https://www.mondoaffariweb.it/media/catalog/product/cache/1/image/1800x/040ec09b1e35df139433887a97daa66f/l/u/lunar-silver_7.jpg"
      ],
       number: "333-444-5555",
       category: "electronics",
       price: 749,
       releaseYear: 2020,
       operatingSystem: "Android 11",
       storageCapacity: ["128GB", "256GB"],
       ram: "8GB",
       screenSize: 6.55,
       batteryCapacity: 4500,
       processor: "Snapdragon 865",
       colorOptions: ["Aquamarine Green", "Lunar Silver"],
       rating: 4.5,
       connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.1", "NFC"],
       weight: 188
     },
     {
       id: 7,
       brand: "Oppo",
       model: "A53",
       imageurl:[
         "https://i.ebayimg.com/images/g/8kwAAOSwc29geKJy/s-l1200.jpg",
         "https://in.static.webuy.com/product_images/Phones/Phones%20Android/SOPPA5364GFBUNLC_l.jpg",
       ],
       number: "444-555-6666",
       category: "electronics",
       price: 199,
       releaseYear: 2020,
       operatingSystem: "Android 10",
       storageCapacity: ["64GB", "128GB"],
       ram: "4GB/6GB",
       screenSize: 6.5,
       batteryCapacity: 5000,
       processor: "Snapdragon 460",
       colorOptions: ["Electric Black", "Fancy Blue"],
       rating: 4.2,
       connectivity: ["4G", "Wi-Fi 5", "Bluetooth 5.0"],
       weight: 186
      },
      {
       id: 8,
       brand: "Asus",
       model: "Zenfone 6",
       imageurl:[
         "https://www.deepspecs.com/wp-content/uploads/2019/05/5-asus-zenfone-6-zs630-kl-deepspecs-com.jpg",
         "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSoGQcQAyrR3TEtvg0Z2hjqz-W8SXul3Pnuw&s",
        ], 
       number: "555-666-7777",
       category: "electronics",
       price: 499,
       releaseYear: 2019,
       operatingSystem: "Android 9 (upgradable to Android 11)",
       storageCapacity: ["64GB", "128GB", "256GB"],
       ram: "6GB/8GB",
       screenSize: 6.4,
       batteryCapacity: 5000,
       processor: "Snapdragon 855",
       colorOptions: ["Midnight Black", "Twilight Silver"],
       rating: 4.4,
       connectivity: ["4G", "Wi-Fi 5", "Bluetooth 5.0", "NFC"],
       weight: 190
      },
      {
       id: 9,
       brand: "Google",
       model: "Pixel 4",
       imageurl:[
        "https://img.tuttoandroid.net/wp-content/uploads/2020/09/Eir8KvGX0AA8ntx.png",
        "https://cdn.shopify.com/s/files/1/0273/7927/3488/products/P4XL-JustBlack-Front_1200x.jpg?v=1570497992",
        "https://img.tuttoandroid.net/wp-content/uploads/2019/10/pixel_4_oh_so_orange_blass_1.jpg"
       ],
       number: "666-777-8888",
       category: "electronics",
       price: 799,
       releaseYear: 2019,
        operatingSystem: "Android 10",
       storageCapacity: ["64GB", "128GB"],
       ram: "6GB",
       screenSize: 5.7,
       batteryCapacity: 2800,
       processor: "Snapdragon 855",
       colorOptions: ["Just Black", "Clearly White", "Oh So Orange"],
       rating: 4.3,
       connectivity: ["4G", "Wi-Fi 5", "Bluetooth 5.0", "NFC"],
       weight: 162
      },
      {
       id: 10,
       brand: "Samsung",
       model: "S20",
       imageurl:[
        "https://th.bing.com/th/id/R.b79867a1dc38cb9a64aff3bcb8b184ac?rik=Z5XrXpwQ6EBsKw&pid=ImgRaw&r=0",
        "https://cdn.alloallo.media/catalog/product/samsung/galaxy-s/galaxy-s20/galaxy-s20-cloud-blue.jpg",
        "https://cdn.alloallo.media/catalog/product/samsung/galaxy-s/galaxy-s20/galaxy-s20-cloud-pink-back.jpg",
       ],
       number: "777-888-9999",
       category: "electronics",
       price: 999,
       releaseYear: 2020,
       operatingSystem: "Android 10",
       storageCapacity: ["128GB"],
       ram: "8GB",
       screenSize: 6.2,
       batteryCapacity: 4000,
       processor: "Exynos 990 / Snapdragon 865",
       colorOptions: ["Cosmic Gray", "Cloud Blue", "Cloud Pink"],
       rating: 4.6,
       connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.0", "NFC"],
       weight: 163
      },
      {
       id: 11,
       brand: "Huawei",
       model: "P40",
       imageurl:[
       "https://thumb.pccomponentes.com/w-530-530/articles/28/281358/huawei-p40-5g-8-128gb-plata-libre-foto.jpg",
       "https://images.eprice.it/nobrand/0/hres/003/209598003/DAM209598003-1-cc3678ac-8438-4240-9c68-ef1615b3385b.jpg",
       "https://www.alezay.com/wp-content/uploads/2020/05/HUAWEI-P40-PRO-5G-DEEP-SEA-BLUE-BACK.jpg"
       ],
       number: "888-999-0000",
       category: "electronics",
       price: 699,
       releaseYear: 2020,
       operatingSystem: "Android 10 (no Google services)",
       storageCapacity: ["128GB", "256GB"],
       ram: "8GB",
       screenSize: 6.1,
       batteryCapacity: 3800,
       processor: "Kirin 990 5G",
       colorOptions: ["Silver Frost", "Blush Gold", "Deep Sea Blue"],
       rating: 4.3,
       connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.1", "NFC"],
       weight: 175
     },
      {
       id: 12,
       brand: "Xiaomi",
       model: "Mi 10",
       imageurl:[
         "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MP_141395089/fee_786_587_png",
         "https://img.gkbcdn.com/s3/p/2020-03-31/Global-Version-Xiaomi-Mi10-5G-Smartphone-8GB-128GB-Twilight-Grey-900716-.jpg",
        ], 
       number: "999-000-1111",
       category: "electronics",
       price: 799,
       releaseYear: 2020,
       operatingSystem: "Android 10",
       storageCapacity: ["128GB", "256GB"],
       ram: "8GB",
       screenSize: 6.67,
       batteryCapacity: 4780,
       processor: "Snapdragon 865",
       colorOptions: ["Coral Green", "Twilight Grey"],
       rating: 4.5,
       connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.1", "NFC"],
       weight: 208
      },
      {
       id: 13,
       brand: "OnePlus",
       model: "8",
       imageurl:[
         "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-8-1.jpg",
         "https://www.mondoaffariweb.it/media/catalog/product/cache/1/image/600x442.91497975709/9df78eab33525d08d6e5fb8d27136e95/g/l/glow_1.jpg",
         "https://i.ytimg.com/vi/GS1pXODxMb4/maxresdefault.jpg"
        ],
       number: "000-111-2222",
       category: "electronics",
       price: 699,
       releaseYear: 2020,
       operatingSystem: "Android 10",
       storageCapacity: ["128GB", "256GB"],
       ram: "8GB/12GB",
       screenSize: 6.55,
       batteryCapacity: 4300,
       processor: "Snapdragon 865",
       colorOptions: ["Glacial Green", "Interstellar Glow", "Onyx Black"],
       rating: 4.4,
       connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.1", "NFC"],
       weight: 180
     },
     {
       id: 14,
       brand: "Oppo",
       model: "A5",
       imageurl:[   
        "https://images-na.ssl-images-amazon.com/images/I/71bmeKzb9HL._AC_SL1500_.jpg",
        "https://cdn.shopify.com/s/files/1/0273/7927/3488/products/Oppo-A5-2020-3_1200x.jpg?v=1570497992",
       ],
       number: "111-222-3333",
       category: "electronics",
       price: 199,
       releaseYear: 2019,
       operatingSystem: "Android 9",
       storageCapacity: ["64GB", "128GB"],
       ram: "3GB/4GB",
       screenSize: 6.5,
       batteryCapacity: 5000,
       processor: "Snapdragon 665",
       colorOptions: ["Mirror Black", "Dazzling White"],
       rating: 4.2,
       connectivity: ["4G", "Wi-Fi 5", "Bluetooth 5.0"],
       weight: 195
     },
     {
       id: 15,
       brand: "Asus",
       model: "Zenfone 5",
       imageurl:[
         "https://fdn2.gsmarena.com/vv/pics/asus/asus-zenfone-5-ze620kl-5z-zs620kl-1.jpg",
         "https://image.alza.cz/products/AST029b/AST029b-02.jpg"
        ],
       number: "222-333-4444",
       category: "electronics",
       price: 399,
       releaseYear: 2018,
       operatingSystem: "Android 8.0",
       storageCapacity: ["64GB", "128GB"],
       ram: "4GB/6GB",
       screenSize: 6.2,
       batteryCapacity: 3300,
       processor: "Snapdragon 636",
       colorOptions: ["Meteor Silver", "Midnight Blue"],
       rating: 4.3,
       connectivity: ["4G", "Wi-Fi 5", "Bluetooth 5.0", "NFC"],
       weight: 155
      },
      {
       id: 16,
       brand: "Nokia",
       model: "Lumia",
       imageurl:[
         "https://i.ebayimg.com/images/g/c2wAAOSwdAtlUyHS/s-l1200.jpg",
         "https://i.ebayimg.com/images/g/xxQAAOSwzilZxD-e/s-l1200.jpg",
         "https://i.ebayimg.com/images/g/BKUAAOSw5epf3Evf/s-l1200.jpg",
         "https://www.smartcellular.co.uk/media/catalog/product/cache/44967087533007dde7246873a72eba7b/8/1/81kwcajnlil._sl1500_.jpg",
        ],
       number: "555-666-8888",
       category: "electronics",
       price: 299,
       releaseYear: 2015,
       operatingSystem: "Windows Phone 8.1",
       storageCapacity: ["8GB", "16GB"],
       ram: "1GB",
       screenSize: 5.0,
       batteryCapacity: 2200,
       processor: "Snapdragon 400",
       colorOptions: ["Black", "White", "Red", "Yellow"],
       rating: 3.8,
       connectivity: ["4G", "Wi-Fi 4", "Bluetooth 4.0"],
       weight: 150
      },
      {
       id: 17,
       brand: "Samsung",
       model: "Galaxy S22 Ultra",
       imageurl:[ 
        "https://it.static.webuy.com/product_images/Telefonia/Cellulari%20-%20Android/SSAMS908BD128GPBLIBC_l.jpg",
        "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MP_144461231?x=536&y=402&format=jpg&quality=80&sp=yes&strip=yes&trim&ex=536&ey=402&align=center&resizesource&unsharp=1.5x1+0.7+0.02&cox=0&coy=0&cdx=536&cdy=402",
        "https://www.notebookcheck.net/fileadmin/Notebooks/News/_nc3/S22_Ultra_Greeen_Untitled.png",
        "https://cdn11.bigcommerce.com/s-uwzrdsm0mg/images/stencil/570x570/products/31491/33748/96941708_4522121614__07711.1715303311.jpg?c=1"
       ],
       number: "555-666-8888",
       category: "electronics",
       price: 1199,
       releaseYear: 2022,
       operatingSystem: "Android 12",
       storageCapacity: ["128GB", "256GB", "512GB", "1TB"],
       ram: "8GB/12GB",
       screenSize: 6.8,
       batteryCapacity: 5000,
       processor: "Snapdragon 8 Gen 1",
       colorOptions: ["Phantom Black", "Phantom White", "Green", "Burgundy"],
       rating: 4.8,
       connectivity: ["5G", "Wi-Fi 6E", "Bluetooth 5.2", "NFC", "Ultra Wideband"],
       weight: 228
      },
      {
       id: 18,
       brand: "OnePlus",
       model: "8 Pro",
       imageurl:[
        "https://down-id.img.susercontent.com/file/a15d076dbbf6a0abc31c0b1437557d58",
        "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-8-pro-1.jpg",
        "https://i.ytimg.com/vi/GS1pXODxMb4/maxresdefault.jpg"
       ],
       number: "666-888-9999",
       category: "electronics",
       price: 899,
       releaseYear: 2020,
       operatingSystem: "Android 10",
       storageCapacity: ["128GB", "256GB"],
       ram: "8GB/12GB",
       screenSize: 6.78,
       batteryCapacity: 4510,
       processor: "Snapdragon 865",
       colorOptions: ["Glacial Green", "Ultramarine Blue", "Onyx Black"],
       rating: 4.6,
       connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.1", "NFC"],
       weight: 199
      },
      {
       id: 19,
       brand: "Google",
       model: "Pixel 5",
       imageurl: "https://static1.pocketnowimages.com/wordpress/wp-content/uploads/styles/xxlarge/public/2021-12/PBI%20Google%20Pixel%205A.png",
       number: "777-888-9999",
       category: "electronics",
       price: 699,
       releaseYear: 2020,
       operatingSystem: "Android 11",
       storageCapacity: ["128GB"],
       ram: "8GB",
       screenSize: 6.0,
       batteryCapacity: 4080,
       processor: "Snapdragon 765G",
       colorOptions: ["Just Black", "Sorta Sage"],
       rating: 4.5,
       connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.0", "NFC"],
       weight: 151
      },
      {
       id: 20,
       brand: "Samsung",
       model: "Galaxy S22",
       imageurl: "https://fscl01.fonpit.de/devices/23/2223.png",
       number: "777-888-9999",
       category: "electronics",
       price: 799,
       releaseYear: 2022,
       operatingSystem: "Android 12",
       storageCapacity: ["128GB", "256GB"],
       ram: "8GB",
       screenSize: 6.1,
       batteryCapacity: 3700,
       processor: "Snapdragon 8 Gen 1",
       colorOptions: ["Phantom Black", "Phantom White", "Green", "Pink Gold"],
       rating: 4.6,
       connectivity: ["5G", "Wi-Fi 6E", "Bluetooth 5.2", "NFC"],
       weight: 167
      },
    
      {
        id: 22,
        brand: "Apple",
        model: "iPhone 15 Pro",
        imageurl: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-pro-finish-select-202309-6-1inch?wid=5120&hei=2880&fmt=p-jpg&qlt=80&.v=1693009279096",
        number: "111-222-3333",
        category: "electronics",
        price: 999,
        releaseYear: 2023,
        operatingSystem: "iOS 17",
        storageCapacity: ["128GB", "256GB", "512GB", "1TB"],
        ram: "8GB",
        screenSize: 6.1,
        batteryCapacity: 3274,
        processor: "A17 Pro",
        colorOptions: ["Black Titanium", "White Titanium", "Blue Titanium", "Natural Titanium"],
        rating: 4.8,
        connectivity: ["5G", "Wi-Fi 6E", "Bluetooth 5.3", "NFC", "Ultra Wideband"],
        weight: 187
      },
      {
        id: 23,
        brand: "Google",
      model: "Pixel 8 Pro",
        imageurl: "https://onecms-res.cloudinary.com/image/upload/v1696589279/mediacorp/8days/image/2023/10/06/03_google_pixel_8_pro_porcelain_bay_obsidian.jpg",
        number: "222-333-4444",
        category: "electronics",
        price: 999,
        releaseYear: 2023,
        operatingSystem: "Android 14",
        storageCapacity: ["128GB", "256GB", "512GB"],
        ram: "12GB",
        screenSize: 6.7,
        batteryCapacity: 5050,
        processor: "Google Tensor G3",
        colorOptions: ["Obsidian", "Porcelain", "Bay"],
        rating: 4.6,
        connectivity: ["5G", "Wi-Fi 7", "Bluetooth 5.3", "NFC", "Ultra Wideband"],
        weight: 213
      },
      {
        id: 24,
        brand: "Xiaomi",
        model: "13 Ultra",
        imageurl: "https://fdn.gsmarena.com/imgroot/reviews/23/xiaomi-13-ultra/inline/-1200/gsmarena_001.jpg",
        number: "333-444-5555",
        category: "electronics",
        price: 1299,
        releaseYear: 2023,
        operatingSystem: "Android 13",
        storageCapacity: ["256GB", "512GB", "1TB"],
        ram: "12GB/16GB",
        screenSize: 6.73,
        batteryCapacity: 5000,
        processor: "Snapdragon 8 Gen 2",
        colorOptions: ["Black", "Green", "White"],
        rating: 4.7,
        connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.3", "NFC", "Infrared"],
        weight: 227
      },
      {
        id: 25,
        brand: "Samsung",
        model: "Galaxy S23 Ultra",
        imageurl: "https://images.samsung.com/is/image/samsung/assets/th/smartphones/galaxy-s23-ultra/images/galaxy-s23-ultra-highlights-kv.jpg",
        number: "444-555-6666",
        category: "electronics",
        price: 1199,
        releaseYear: 2023,
        operatingSystem: "Android 13",
        storageCapacity: ["256GB", "512GB", "1TB"],
        ram: "12GB",
        screenSize: 6.8,
        batteryCapacity: 5000,
        processor: "Snapdragon 8 Gen 2",
        colorOptions: ["Phantom Black", "Green", "Lavender", "Cream"],
        rating: 4.8,
        connectivity: ["5G", "Wi-Fi 6E", "Bluetooth 5.3", "NFC", "Ultra Wideband"],
        weight: 234
      },
      {
        id: 26,
        brand: "Apple",
        model: "iPhone 14",
        imageurl: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-14-finish-select-202209-6-1inch-midnight?wid=5120&hei=2880&fmt=p-jpg&qlt=80&.v=1661027208726",
        number: "555-666-7777",
        category: "electronics",
        price: 799,
        releaseYear: 2022,
        operatingSystem: "iOS 16",
        storageCapacity: ["128GB", "256GB", "512GB"],
        ram: "6GB",
        screenSize: 6.1,
        batteryCapacity: 3279,
        processor: "A15 Bionic",
        colorOptions: ["Midnight", "Purple", "Starlight", "Blue", "Red"],
        rating: 4.6,
        connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.3", "NFC"],
        weight: 172
      },
      {
        id: 27,
        brand: "Google",
        model: "Pixel 7a",
        imageurl: "https://static1.pocketlintimages.com/wordpress/wp-content/uploads/2023/04/google-pixel-7a-leaked-press-image-in-grey.jpg",
        number: "666-777-8888",
        category: "electronics",
        price: 499,
        releaseYear: 2023,
        operatingSystem: "Android 13",
        storageCapacity: ["128GB"],
        ram: "8GB",
        screenSize: 6.1,
        batteryCapacity: 4385,
        processor: "Google Tensor G2",
        colorOptions: ["Charcoal", "Snow", "Sea", "Coral"],
        rating: 4.4,
        connectivity: ["5G", "Wi-Fi 6E", "Bluetooth 5.3", "NFC"],
        weight: 193
      },
      {
        id: 28,
        brand: "Xiaomi",
        model: "12T Pro",
        imageurl: "https://imgs.hipertextual.com/wp-content/uploads/2022/10/xiaomi-12-t-pro-001.jpg",
        number: "777-888-9999",
        category: "electronics",
        price: 749,
        releaseYear: 2022,
        operatingSystem: "Android 12",
        storageCapacity: ["128GB", "256GB"],
        ram: "8GB/12GB",
        screenSize: 6.67,
        batteryCapacity: 5000,
        processor: "Snapdragon 8+ Gen 1",
        colorOptions: ["Black", "Blue", "Silver"],
        rating: 4.5,
        connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.2", "NFC", "Infrared"],
        weight: 205
      },
      {
        id: 29,
        brand: "Samsung",
        model: "Galaxy Z Flip5",
        imageurl: "https://citynomads.com/wp-content/uploads/2023/10/Samsung-Galaxy-Z-Flip5-Header.png",
      number: "888-999-0000",
        category: "electronics",
        price: 999,
        releaseYear: 2023,
        operatingSystem: "Android 13",
        storageCapacity: ["256GB", "512GB"],
        ram: "8GB",
        screenSize: 6.7,
        batteryCapacity: 3700,
        processor: "Snapdragon 8 Gen 2",
        colorOptions: ["Mint", "Graphite", "Cream", "Lavender", "Gray"],
        rating: 4.3,
        connectivity: ["5G", "Wi-Fi 6E", "Bluetooth 5.3", "NFC"],
        weight: 187
      },
      {
        id: 30,
        brand: "Apple",
        model: "iPhone SE (2022)",
        imageurl: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-se-finish-select-202207-midnight?wid=5120&hei=2880&fmt=p-jpg&qlt=80&.v=1656648332708",
        number: "999-000-1111",
        category: "electronics",
        price: 429,
        releaseYear: 2022,
        operatingSystem: "iOS 15",
        storageCapacity: ["64GB", "128GB", "256GB"],
        ram: "4GB",
        screenSize: 4.7,
        batteryCapacity: 2018,
        processor: "A15 Bionic",
        colorOptions: ["Midnight", "Starlight", "Red"],
        rating: 4.2,
        connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.0", "NFC"],
        weight: 144
      },
      {
        id: 31,
        brand: "Google",
        model: "Pixel Fold",
        imageurl: "https://cdn.mos.cms.futurecdn.net/YsiuahP9uxqcTwzJubBS3A.jpg",
        number: "000-111-2222",
        category: "electronics",
        price: 1799,
        releaseYear: 2023,
        operatingSystem: "Android 13",
        storageCapacity: ["256GB", "512GB"],
        ram: "12GB",
        screenSize: 7.6,
        batteryCapacity: 4821,
        processor: "Google Tensor G2",
        colorOptions: ["Obsidian", "Porcelain"],
        rating: 4.3,
        connectivity: ["5G", "Wi-Fi 6E", "Bluetooth 5.2", "NFC"],
        weight: 283
      },
      {
        id: 32,
        brand: "Xiaomi",
        model: "Redmi Note 12 Pro",
        imageurl: "https://cdnx.jumpseller.com/ponto24business/image/30676622/resize/1200/1200?1672857207",
        number: "123-456-7890",
        category: "electronics",
        price: 299,
        releaseYear: 2022,
        operatingSystem: "Android 12",
        storageCapacity: ["128GB", "256GB"],
        ram: "6GB/8GB",
        screenSize: 6.67,
        batteryCapacity: 5000,
        processor: "MediaTek Dimensity 1080",
        colorOptions: ["Onyx Gray", "Ice Blue", "Forest Green"],
        rating: 4.4,
        connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.2", "NFC"],
        weight: 187
      },
      {
        id: 33,
        brand: "Samsung",
        model: "Galaxy A54",
        imageurl: "https://img.global.news.samsung.com/in/wp-content/uploads/2023/03/A54-A34-creative.jpg",
        number: "234-567-8901",
        category: "electronics",
        price: 449,
        releaseYear: 2023,
        operatingSystem: "Android 13",
        storageCapacity: ["128GB", "256GB"],
        ram: "6GB/8GB",
        screenSize: 6.4,
        batteryCapacity: 5000,
        processor: "Exynos 1380",
        colorOptions: ["Awesome Black", "Awesome White", "Awesome Violet", "Awesome Lime"],
        rating: 4.5,
        connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.3", "NFC"],
        weight: 202
      },
      {
        id: 34,
        brand: "Apple",
        model: "iPhone 13 mini",
        imageurl: "https://mediashop2.com/wp-content/uploads/2022/10/iphone-13-mini-family-select-2.webp",
        number: "345-678-9012",
        category: "electronics",
        price: 599,
        releaseYear: 2021,
        operatingSystem: "iOS 15",
        storageCapacity: ["128GB", "256GB", "512GB"],
        ram: "4GB",
        screenSize: 5.4,
        batteryCapacity: 2406,
        processor: "A15 Bionic",
        colorOptions: ["Pink", "Blue", "Midnight", "Starlight", "Green", "Red"],
        rating: 4.7,
        connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.0", "NFC"],
        weight: 140
      },
      {
        id: 35,
        brand: "Google",
        model: "Pixel 6a",
        imageurl: "https://futurewithtech.com/wp-content/uploads/2022/07/Google-Pixel-6a.jpg",
        number: "456-789-0123",
        category: "electronics",
        price: 349,
        releaseYear: 2022,
        operatingSystem: "Android 12",
        storageCapacity: ["128GB"],
        ram: "6GB",
        screenSize: 6.1,
        batteryCapacity: 4410,
        processor: "Google Tensor",
        colorOptions: ["Chalk", "Charcoal", "Sage"],
        rating: 4.5,
        connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.2", "NFC"],
        weight: 178
      },
      {
        id :36,
        brand: "Xiaomi",
        model: "POCO F5",
        imageurl: "https://th.bing.com/th/id/R.16b543c81f35572bca79b82418a73160?rik=agV9Tc83mvvFXg&pid=ImgRaw&r=0",
        number: "567-890-1234",
        category: "electronics",
        price: 379,
        releaseYear: 2023,
        operatingSystem: "Android 13",
        storageCapacity: ["128GB", "256GB"],
        ram: "8GB/12GB",
        screenSize: 6.67,
        batteryCapacity: 5000,
        processor: "Snapdragon 7+ Gen 2",
        colorOptions: ["Black", "Blue", "White"],
        rating: 4.6,
        connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.3", "NFC"],
        weight: 181
      },
      {
        id: 37,
        brand: "Samsung",
        model: "Galaxy Z Fold5",
        imageurl: "https://images.samsung.com/in/smartphones/galaxy-z-fold5/images/galaxy-z-fold5-highlights-kv-a.jpg?imbypass=true",
        number: "678-901-2345",
        category: "electronics",
        price: 1799,
        releaseYear: 2023,
        operatingSystem: "Android 13",
        storageCapacity: ["256GB", "512GB", "1TB"],
        ram: "12GB",
        screenSize: 7.6,
        batteryCapacity: 4400,
        processor: "Snapdragon 8 Gen 2",
        colorOptions: ["Icy Blue", "Phantom Black", "Cream", "Gray", "Blue"],
        rating: 4.4,
        connectivity: ["5G", "Wi-Fi 6E", "Bluetooth 5.3", "NFC", "Ultra Wideband"],
        weight: 253
      },
      {
        id: 38,
        brand: "Apple",
        model: "iPhone 12",
        imageurl: "https://assets-prd.ignimgs.com/2020/10/13/screen-shot-2020-10-13-at-2-03-33-pm-1602612536531.JPG",
        number: "789-012-3456",
        category: "electronics",
        price: 699,
        releaseYear: 2020,
        operatingSystem: "iOS 14",
        storageCapacity: ["64GB", "128GB", "256GB"],
        ram: "4GB",
        screenSize: 6.1,
        batteryCapacity: 2815,
        processor: "A14 Bionic",
        colorOptions: ["Black", "White", "Red", "Green", "Blue", "Purple"],
        rating: 4.6,
        connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.0", "NFC"],
        weight: 164
      },
      {
        id: 39,
        brand: "Google",
        model: "Pixel 5a",
        imageurl: "https://p.turbosquid.com/ts-thumb/jA/ydz2cn/7e/1200/jpg/1682931905/600x600/fit_q87/94d3944bb27c5f828acca21d491cf998286d39dc/1200.jpg",
        number: "890-123-4567",
        category: "electronics",
        price: 449,
        releaseYear: 2021,
        operatingSystem: "Android 11",
        storageCapacity: ["128GB"],
        ram: "6GB",
        screenSize: 6.34,
        batteryCapacity: 4680,
        processor: "Snapdragon 765G",
        colorOptions: ["Mostly Black"],
        rating: 4.3,
        connectivity: ["5G", "Wi-Fi 5", "Bluetooth 5.0", "NFC"],
        weight: 183
      },
      {
        id: 40,
        brand: "Xiaomi",
        model: "Black Shark 5 Pro",
        imageurl: "https://www.notebookcheck.nl/fileadmin/_processed_/5/a/csm_BS5_Two_colors_6ce410d6b2.jpg",
        number: "901-234-5678",
        category: "electronics",
        price: 799,
        releaseYear: 2022,
        operatingSystem: "Android 12",
        storageCapacity: ["256GB", "512GB"],
        ram: "8GB/12GB/16GB",
        screenSize: 6.67,
        batteryCapacity: 4650,
        processor: "Snapdragon 8 Gen 1",
        colorOptions: ["Black", "White"],
      rating: 4.7,
        connectivity: ["5G", "Wi-Fi 6", "Bluetooth 5.2", "NFC"],
        weight: 220
      }
    
    

];


// Search endpoint
app.get('/search', (req, res) => {
  const query = req.query.q ? req.query.q.toString().toLowerCase() : '';
  console.log('Searching for: ', query);

  if(!query) {
   res.json(phoneListings);
  }

  const results = phoneListings.filter(phone => 
    phone.brand.toLowerCase().includes(query) || 
    phone.model.toLowerCase().includes(query)
  );
  console.log('Found results: ', results.length);
  res.json(results);
});

// Get all phones
app.get('/phoneListings', (req, res) => {
  res.json(phoneListings);
});

// Get single phone
app.get('/phoneListings/:id', (req, res) => {
  const id = parseInt(req.params.id);
  const phone = phoneListings.find(p => p.id === id);
  if (!phone) res.status(404).json({ error: 'Phone not found' });
  res.json(phone);
});

// Create new phone
app.post('/phoneListings', (req, res) => {
  const { brand, model, imageurl, number, category, price, releaseYear, operatingSystem, storageCapacity, ram } = req.body;
  if (!brand || !model || !imageurl || !number || !category) {
   res.status(400).json({ error: 'Invalid phone data' });
  }
  
  const newPhone = {
    id: phoneListings.length + 1,
    brand,
    model,
    imageurl,
    number,
    category,
    price: price || null,
    releaseYear: releaseYear || null,
    operatingSystem: operatingSystem || null,
    storageCapacity: storageCapacity || [],
    ram: ram || null
  };

  phoneListings.push(newPhone);
  res.status(201).json(newPhone);
});

app.listen(port, () => {
  console.log(`API running at http://localhost:${port}`);
});